apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-pagamento-config
data:
  DATABASE_URL: ${DATABASE_URL}
  MYSQL_DATABASE: goodburguer
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-pagamento-secret
type: Opaque
data:
  DATABASE_USERNAME: YWRtaW4=
  DATABASE_PASSWORD: WXZuWDRuSmpydE9XN3Z5Uk5MZlVl